// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: env("postgresql://neondb_owner:npg_1k2VxilBrEHc@ep-summer-recipe-a46102zv-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"),
  },
});
